### ISSUE TITLE
No need to wait after Wire.requestFrom().

### ISSUE THREAD

**Issue by Koepel** [amperka/Octoliner#6]
In the file "src/Octoliner.cpp" there is a while-loop with `Wire.available()` after a `Wire.requestFrom()`.
That while-loop may be removed.
Explanation: [Common-mistakes#1](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes#1)

The code as it is now can detect when a sensor is not connected. That functionality can be kept this way:
```
    Wire.requestFrom(_i2caddress, byteCount);
    if (Wire.available() != byteCount)
    {
        return result;
    }
```

**Comment by yurybotov** [comment]
Done
